name: "Legacy release"

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: legacy-greed-release
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml

  ghcrio:
    uses: Steffo99/.github/.github/workflows/buildrelease-docker.yml@main
    needs:
      - test
