name: "Legacy test suite"

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: legacy-greed-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: Steffo99/.github/.github/workflows/test-poetry-compileall.yml@main
